server:
  port: 8081
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/strr_admin?serverTimezone=UTC
    username: root
    password: password
# 下划线驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
